---
- hosts: local
  gather_facts: false

  vars_files:
  - ./vars/vault.yml
  - ./vars/vars.yml

  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    # or use aws_access_key/aws_secret_key parameters on ec2 module instead

  tasks:
  - name: Create an instance
    ec2:
      instance_type: t2.micro
      image: ami-a15e0db6
      wait: yes
      group: launch-wizard-1
      count: 1
      key_name: Anisble_AWS_tmp
      region: eu-west-2a
      instance_tags:
        Name: pristine-api instance
    # Could be useful further to get Public IP, DNS, etc.
    register: ec2

  # debug the output to see what AWS returns back
  - debug: var=ec2
